# Generated by Django 5.0.6 on 2024-09-21 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
